version: '3.8'

services:
  main-app:
    build:
      context: .
      dockerfile: apps/main-app/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - vue3-micro-app
      - react-micro-app
      - vue2-micro-app
    networks:
      - micro-frontend-net

  vue3-micro-app:
    build:
      context: .
      dockerfile: apps/vue3-micro-app/Dockerfile
    ports:
      - "3003:80"
    networks:
      - micro-frontend-net

  react-micro-app:
    build:
      context: .
      dockerfile: apps/react-micro-app/Dockerfile
    ports:
      - "3004:80"
    networks:
      - micro-frontend-net

  vue2-micro-app:
    build:
      context: .
      dockerfile: apps/vue2-micro-app/Dockerfile
    ports:
      - "3002:80"
    networks:
      - micro-frontend-net

networks:
  micro-frontend-net:
    driver: bridge
